site_name: 理解すること  〜初学者のための10の質問〜
docs_dir: markdown_jp

theme:
  name: readthedocs
  language: ja
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest

nav:
  - ホーム: index.md
  - まえがき: preface.md
  - 第1章 認識・情報:
      - 1.1 問1: 1-1.md
      - 1.2 観測・情報: 1-2.md
      - 1.3 知覚・認識: 1-3.md
      - 1.4 概念の形成と定義: 1-4.md
  - 第2章 分類・整理:
      - 2.1 問2: 2-1.md
      - 2.2 比較: 2-2.md
      - 2.3 分類・整理: 2-3.md
      - 2.4 情報の構造化: 2-4.md
      - 2.5 データ型・データベース（参考）: 2-5.md
  - 第3章 論理・演算:
      - 3.1 問3: 3-1.md
      - 3.2 集合・論理: 3-2.md
      - 3.3 命題・論理: 3-3.md
      - 3.4 数学的構造: 3-4.md
      - 3.5 数・演算: 3-5.md
  - 第4章 過程・因果:
      - 4.1 問4: 4-1.md
      - 4.2 プロセス: 4-2.md
      - 4.3 情報処理: 4-3.md
  - 第5章 組織・システム:
      - 5.1 問5: 5-1.md
      - 5.2 構成: 5-2.md
      - 5.3 分析アプローチ: 5-3.md
      - 5.4 秩序・安定: 5-4.md
      - 5.5 変動: 5-5.md
      - 5.6 システムの理解と運用の難しさ: 5-6.md
  - 第6章 仮説・検証:
      - 6.1 問6: 6-1.md
      - 6.2 科学・仮説・実証: 6-2.md
      - 6.3 実験系の設定: 6-3.md
      - 6.4 測定・分析: 6-4.md
      - 6.5 生産管理・品質管理（参考）: 6-5.md
  - 第7章 モデリング・推論:
      - 7.1 問7: 7-1.md
      - 7.2 モデリング: 7-2.md
      - 7.3 数理モデル: 7-3.md
      - 7.4 解釈・評価: 7-4.md
      - 7.5 因果推論: 7-5.md
      - 7.6 数理モデルの応用分野例（参考）: 7-6.md
  - 第8章 意味・価値:
      - 8.1 問8: 8-1.md
      - 8.2 意味: 8-2.md
      - 8.3 価値: 8-3.md
      - 8.4 表現: 8-4.md
  - 第9章 議論・意思決定:
      - 9.1 問9: 9-1.md
      - 9.2 議論: 9-2.md
      - 9.3 合意形成: 9-3.md
      - 9.4 議論・合意形成の不調: 9-4.md
  - 第10章 コンピューター:
      - 10.1 問10: 10-1.md
      - 10.2 執筆中: 10-2.md
      - 10.3 執筆中: 10-3.md
      - 10.4 執筆中: 10-4.md
      - 10.5 執筆中: 10-5.md
  - あとがき: afterword.md


